<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeployNexus.Domain\DeployNexus.Domain.csproj" />
    <ProjectReference Include="..\DeployNexus.Shared\DeployNexus.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\Interfaces\" />
    <Folder Include="Modules\DTOs\" />
    <Folder Include="Modules\Services\" />
    <Folder Include="Organizations\DTOs\" />
    <Folder Include="Organizations\Interfaces\" />
    <Folder Include="Organizations\Services\" />
    <Folder Include="Permissions\Interfaces\" />
    <Folder Include="Permissions\DTOs\" />
    <Folder Include="Permissions\Services\" />
    <Folder Include="Roles\Interfaces\" />
    <Folder Include="Roles\DTOs\" />
    <Folder Include="Roles\Services\" />
  </ItemGroup>

</Project>
